import React, { useEffect, useRef, useState } from 'react';
import { Text, Pressable } from 'react-native';
import * as Notifications from 'expo-notifications';
import { useStartFocusSession, useEndFocusSession, useListFocusSessions } from '@workspace/api-client-react';
import { Button, Card, Screen, State, styles } from '@/components/native-ui';
import { useColors } from '@/hooks/useColors';
import { useNotificationPreferences } from '@/context/NotificationPreferences';
const durations = [15, 25, 45, 60, 90];
export default function Focus() {
  const colors = useColors(); const { preferences } = useNotificationPreferences(); const [name, setName] = useState('Focused study'); const [minutes, setMinutes] = useState(25); const [running, setRunning] = useState(false); const [started, setStarted] = useState(0); const [id, setId] = useState<number | null>(null); const [seconds, setSeconds] = useState(0); const notification = useRef<string | null>(null); const finalized = useRef(false); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const start = useStartFocusSession(); const end = useEndFocusSession(); const history = useListFocusSessions({ sort: 'desc' });
  const finalize = async (elapsedSeconds: number) => { if (id == null || finalized.current) return; finalized.current = true; if (notification.current) { await Notifications.cancelScheduledNotificationAsync(notification.current).catch(() => undefined); notification.current = null; } end.mutate({ id, data: { durationMinutes: Math.max(1, Math.round(elapsedSeconds / 60)) } }, { onSuccess: () => { setRunning(false); history.refetch(); } }); };
  useEffect(() => { if (running) timer.current = setInterval(() => { const elapsed = Math.floor((Date.now() - started) / 1000); setSeconds(elapsed); if (elapsed >= minutes * 60) void finalize(elapsed); }, 1000); return () => { if (timer.current) clearInterval(timer.current); }; }, [running, started, minutes, id]);
  const begin = () => start.mutate({ data: { name, sessionType: 'study' } }, { onSuccess: async (x) => { finalized.current = false; setId(x.id); setStarted(Date.now()); setSeconds(0); setRunning(true); if (preferences.enabled) notification.current = await Notifications.scheduleNotificationAsync({ content: { title: 'Focus session complete', body: `Your ${minutes}-minute session is complete.`, data: { route: '/focus', managedBy: 'bloom-focus' } }, trigger: { type: Notifications.SchedulableTriggerInputTypes.DATE, date: new Date(Date.now() + minutes * 60 * 1000) } }); } });
  const finish = async () => { await finalize(seconds); };
  return <Screen title="Focus"><Card><Text style={{ color: colors.mutedForeground }}>Choose a session length, then put your phone down.</Text><Text testID="focus-timer" style={{ color: colors.foreground, fontSize: 54, fontWeight: '700', textAlign: 'center', marginVertical: 18 }}>{String(Math.floor(seconds / 60)).padStart(2, '0')}:{String(seconds % 60).padStart(2, '0')}</Text><Text style={{ color: colors.mutedForeground }}>Duration</Text><Pressable style={styles.row}>{durations.map((x) => <Button key={x} testID={`focus-duration-${x}`} onPress={() => !running && setMinutes(x)}>{minutes === x ? `✓ ${x}m` : `${x}m`}</Button>)}</Pressable><Button testID="focus-toggle" onPress={running ? finish : begin}>{running ? 'End session' : `Start ${minutes}-minute focus`}</Button></Card><State loading={history.isLoading} error={history.error} />{history.data?.slice(0, 5).map((x) => <Card key={x.id}><Text style={{ color: colors.foreground, fontWeight: '700' }}>{x.name}</Text><Text style={{ color: colors.mutedForeground }}>{x.durationMinutes ?? 0} minutes</Text></Card>)}</Screen>;
}